export const GET_PRIMARY_TEXT = 'GET_PRIMARY_TEXT';
export const SET_PRIMARY_TEXT = 'SET_PRIMARY_TEXT';
export const GET_SECONDARY_TEXT = 'GET_SECONDARY_TEXT';
export const SET_SECONDARY_TEXT = 'SET_SECONDARY_TEXT';
export const GET_FINE_PRINT = 'GET_FINE_PRINT';
export const SET_FINE_PRINT = 'SET_FINE_PRINT';